
name: Create Tweets update Posts and build Hugo
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - 'update'

jobs:
  scanFilesAndTweet:
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        ref: update
    - uses: actions/setup-python@v2 #load right python version
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: pip install -r ./.github/workflows/requirements.txt
    - name: Run a one-line script
      run: python ./.github/workflows/main.py -c ${{secrets.CONSUMER_KEY}} -s ${{secrets.CONSUMER_SECRET}} -t ${{secrets.ACCESS_TOKEN}} -o ${{secrets.ACCESS_TOKEN_SECRET}} #important to call python from current folder, avoids issues with pathfinding

    #####run hugo build command ####
    - name: Hugo Action
      uses: srt32/hugo-action@master
      #args: <Hugo args> #optional - i do not need it just build

    ####commit changes to update ####
    - name: git config
      run: git config --local user.email "action@github.com"
    - name: git config
      run: git config --local user.name "GitHub Action"
    - name: git add --all
      run: git add --all
    - name: status
      run: git status
    - name: git commit
      run: git commit -m "Updated posts with Tweet handles" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'update'

  ####### Merge master & update and push to master
  mergeUpdateToMasterCommit:
      needs: [scanFilesAndTweet] #ensure job is only running after scanFilesAndTweet
      # This job runs on Linux
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2 #checkout master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: master
      - name: git config
        run: git config --local user.email "action@github.com"
      - name: git config
        run: git config --local user.name "GitHub Action"
      - name: git merge origin/update
        run: git merge origin/update
      - name: status
        run: git status
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.        github_token: ${{ secrets.GITHUB_TOKEN }} #ATTENTION if GITHUB_TOKEN is used then no push actions are triggered. You need to use your personal token to trigger this => PERSONAL_TOKEN
          branch: 'master'
