name: Deploy to firebase
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - 'master'

jobs:
  hugoDeployToFirebase: #maybe just add this on master push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 #checkout master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        ref: master
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: theprogress-83b4d
