name: Merge update branch to Master
on:
  push:
    branches:
      - 'update'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        ref: update
    - name: change file
      run: echo "wow2" >> content/posts/test1.md
    - name: git config
      run: git config --local user.email "action@github.com"
    - name: git config
      run: git config --local user.name "GitHub Action"
    - name: git add --all
      run: git add --all
    - name: status
      run: git status
    - name: git commit
      run: git commit -m "Updated posts with Tweet handles" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'update'
    - uses: actions/checkout@v2 #checkout master
      with:
        ref: master
    - name: Merge to master branch
      uses: devmasx/merge-branch@v1.1.0
      with:
        type: now
        target_branch: 'update'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
